// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_querries.sql

package identitydb

import (
	"context"
	"database/sql"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, password_hash, email, role FROM users 
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (username, password_hash, email, role)
VALUES ($1, $2, $3, $4)
`

type InsertUserParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	Role         string         `json:"role"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.Role,
	)
	return err
}
