// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"database/sql"
)

type User struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	Role         string         `json:"role"`
}
