// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library_queries.sql

package librarydb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const decreaseBookCount = `-- name: DecreaseBookCount :one
UPDATE library_books
SET available_count = available_count - 1
WHERE library_id = (SELECT id FROM library WHERE library_uid = $1)
  AND book_id = (SELECT id FROM books WHERE book_uid = $2)
  AND available_count > 0
  RETURNING book_id, library_id, available_count
`

type DecreaseBookCountParams struct {
	LibraryUid uuid.UUID `json:"library_uid"`
	BookUid    uuid.UUID `json:"book_uid"`
}

func (q *Queries) DecreaseBookCount(ctx context.Context, arg DecreaseBookCountParams) (LibraryBook, error) {
	row := q.db.QueryRowContext(ctx, decreaseBookCount, arg.LibraryUid, arg.BookUid)
	var i LibraryBook
	err := row.Scan(&i.BookID, &i.LibraryID, &i.AvailableCount)
	return i, err
}

const getAllLibraries = `-- name: GetAllLibraries :many
SELECT id, library_uid, name, city, address FROM library
WHERE ($1::text IS NULL OR city = $1)
`

func (q *Queries) GetAllLibraries(ctx context.Context, dollar_1 string) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, getAllLibraries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.LibraryUid,
			&i.Name,
			&i.City,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBook = `-- name: GetBook :one
SELECT id, book_uid, name, author, genre, condition FROM books 
WHERE book_uid = $1
`

func (q *Queries) GetBook(ctx context.Context, bookUid uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, bookUid)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.BookUid,
		&i.Name,
		&i.Author,
		&i.Genre,
		&i.Condition,
	)
	return i, err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, library_uid, name, city, address FROM library
WHERE library_uid = $1
`

func (q *Queries) GetLibrary(ctx context.Context, libraryUid uuid.UUID) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, libraryUid)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.LibraryUid,
		&i.Name,
		&i.City,
		&i.Address,
	)
	return i, err
}

const getLibraryBooks = `-- name: GetLibraryBooks :many
SELECT book_id, library_id, available_count, l.id, library_uid, l.name, city, address, b.id, book_uid, b.name, author, genre, condition
FROM library_books lb
JOIN library l ON lb.library_id = l.id
JOIN books b ON lb.book_id = b.id
WHERE l.library_uid = $1
`

type GetLibraryBooksRow struct {
	BookID         sql.NullInt32  `json:"book_id"`
	LibraryID      sql.NullInt32  `json:"library_id"`
	AvailableCount int32          `json:"available_count"`
	ID             int32          `json:"id"`
	LibraryUid     uuid.UUID      `json:"library_uid"`
	Name           string         `json:"name"`
	City           string         `json:"city"`
	Address        string         `json:"address"`
	ID_2           int32          `json:"id_2"`
	BookUid        uuid.UUID      `json:"book_uid"`
	Name_2         string         `json:"name_2"`
	Author         sql.NullString `json:"author"`
	Genre          sql.NullString `json:"genre"`
	Condition      sql.NullString `json:"condition"`
}

func (q *Queries) GetLibraryBooks(ctx context.Context, libraryUid uuid.UUID) ([]GetLibraryBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getLibraryBooks, libraryUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLibraryBooksRow
	for rows.Next() {
		var i GetLibraryBooksRow
		if err := rows.Scan(
			&i.BookID,
			&i.LibraryID,
			&i.AvailableCount,
			&i.ID,
			&i.LibraryUid,
			&i.Name,
			&i.City,
			&i.Address,
			&i.ID_2,
			&i.BookUid,
			&i.Name_2,
			&i.Author,
			&i.Genre,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
