// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library_queries.sql

package librarydb

import (
	"context"
)

const getAllLibraries = `-- name: GetAllLibraries :many
SELECT id, library_uid, name, city, address FROM library
WHERE ($1::text IS NULL OR city = $1)
`

func (q *Queries) GetAllLibraries(ctx context.Context, dollar_1 string) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, getAllLibraries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.LibraryUid,
			&i.Name,
			&i.City,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
