replicaCount: 1

image:
  repository: ""
  tag: "v1"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: yc-registry-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  host: ""
  path: /
  pathType: Prefix
  annotations: {}

env: []

extraVolumes: []
extraVolumeMounts: []

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

livenessProbe:
  enabled: false
  path: /manage/health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /manage/health
  initialDelaySeconds: 10
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}
extraVolumes: []
extraVolumeMounts: []