# ---- Сборка приложения ----
FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/identity ./cmd/identity
COPY internal ./internal
# (строка COPY internal/models ./models удалена)

RUN CGO_ENABLED=0 GOOS=linux go build -p 1 -o /go/bin/app ./cmd/identity

# ---- Финальный образ ----
FROM alpine:3.20

RUN apk add --no-cache ca-certificates postgresql-client

# Устанавливаем goose
ADD https://github.com/pressly/goose/releases/latest/download/goose_linux_x86_64 /usr/local/bin/goose
RUN chmod +x /usr/local/bin/goose

COPY --from=builder /go/bin/app /app
COPY postgres/schema/identity_service /migrations
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8090
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/app"]