FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/gateway ./cmd/gateway
COPY internal ./internal
COPY internal/models ./internal/models

RUN CGO_ENABLED=0 GOOS=linux go build -p 1 -o /go/bin/app ./cmd/gateway

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/app /app
EXPOSE 8080
CMD ["/app"]