# ---- Сборка приложения ----
FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/reservation ./cmd/reservation
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux go build -p 1 -o /go/bin/app ./cmd/reservation

# ---- Финальный образ ----
FROM alpine:3.20

RUN apk add --no-cache ca-certificates postgresql-client

ADD https://github.com/pressly/goose/releases/latest/download/goose_linux_x86_64 /usr/local/bin/goose
RUN chmod +x /usr/local/bin/goose

COPY --from=builder /go/bin/app /app

# Копируем миграции для резерваций
COPY postgres/schema/reservation_service /migrations

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8070
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/app"]