// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reservationdb

import (
	"time"

	"github.com/google/uuid"
)

type Reservation struct {
	ID             int32     `json:"id"`
	ReservationUid uuid.UUID `json:"reservation_uid"`
	Username       string    `json:"username"`
	BookUid        uuid.UUID `json:"book_uid"`
	LibraryUid     uuid.UUID `json:"library_uid"`
	Status         string    `json:"status"`
	StartDate      time.Time `json:"start_date"`
	TillDate       time.Time `json:"till_date"`
}
