// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_queries.sql

package reservationdb

import (
	"context"
)

const init = `-- name: Init :exec
SELECT id, reservation_uid, username, book_uid, library_uid, status, start_date, till_date FROM reservation
`

func (q *Queries) Init(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, init)
	return err
}
