// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratingdb

type Rating struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Stars    int32  `json:"stars"`
}
