// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rating_queries.sql

package ratingdb

import (
	"context"
)

const getUserStars = `-- name: GetUserStars :one
SELECT stars FROM rating
WHERE username = $1
`

func (q *Queries) GetUserStars(ctx context.Context, username string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserStars, username)
	var stars int32
	err := row.Scan(&stars)
	return stars, err
}
