// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rating_queries.sql

package ratingdb

import (
	"context"
)

const init = `-- name: Init :exec
SELECT id, username, stars FROM rating
`

func (q *Queries) Init(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, init)
	return err
}
