// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rating_queries.sql

package ratingdb

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO rating (username, stars)
VALUES ($1, $2)
`

type CreateUserParams struct {
	Username string `json:"username"`
	Stars    int32  `json:"stars"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Stars)
	return err
}

const getUserStars = `-- name: GetUserStars :one
SELECT stars FROM rating
WHERE username = $1
`

func (q *Queries) GetUserStars(ctx context.Context, username string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserStars, username)
	var stars int32
	err := row.Scan(&stars)
	return stars, err
}

const updateRating = `-- name: UpdateRating :exec
UPDATE rating
SET stars = stars + $1
WHERE username = $2
`

type UpdateRatingParams struct {
	Stars    int32  `json:"stars"`
	Username string `json:"username"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateRating, arg.Stars, arg.Username)
	return err
}
