// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package librarydb

import (
	"database/sql"

	"github.com/google/uuid"
)

type Book struct {
	ID        int32          `json:"id"`
	BookUid   uuid.UUID      `json:"book_uid"`
	Name      string         `json:"name"`
	Author    sql.NullString `json:"author"`
	Genre     sql.NullString `json:"genre"`
	Condition sql.NullString `json:"condition"`
}

type Library struct {
	ID         int32     `json:"id"`
	LibraryUid uuid.UUID `json:"library_uid"`
	Name       string    `json:"name"`
	City       string    `json:"city"`
	Address    string    `json:"address"`
}

type LibraryBook struct {
	BookID         sql.NullInt32 `json:"book_id"`
	LibraryID      sql.NullInt32 `json:"library_id"`
	AvailableCount int32         `json:"available_count"`
}
